version: '3'
services:
  web:
    volumes:
      - ./app:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000

      - MONGO_DB_BASE=scra
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017

      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=6379
    depends_on:
      - mongo
      - redis
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:xenial"
